#!/usr/bin/env python
"""
Split a charge amongst my roommates.
"""
import argparse

import venmo

ROOMMATES = {
    '@nicholas-lippis',
    '@dylan-harris-3',
    '@robert-garbanati',
    '@zmorris',
    '@traplord',
    '@ben-hunter-3',
    '@Claire-Redemer',
}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('total', help='total fee to split', type=float)
    parser.add_argument('note', help='note for the charge')
    args = parser.parse_args()
    amount = float('{:.2f}'.format(args.total / (len(ROOMMATES) + 1)))
    note = args.note
    for roommate in ROOMMATES:
        venmo.payment.charge(roommate, amount, note)


if __name__ == '__main__':
    main()
