#!/usr/bin/env bash -e

helpmsg() {
  echo "Usage: ./roommates <amount> <note>"
  exit 1
}

if [ -z "$1" ]; then
  helpmsg
else
  amount=$1
  shift
fi

if [ -z "$1" ]; then
  helpmsg
else
  note=$1
  shift
fi

roommates=(
  "@nicholas-lippis"
  "@dylan-harris-3"
  "@robert-garbanati"
  "@zmorris"
  "@traplord"
  # "@ben-hunter-3"
  # "@ben-lurie"
)

num_roommates=$(( ${#roommates[@]} + 1 ))  # including me
cost_per=$(python -c "from math import ceil; print '{0:.2f}'.format($amount/float($num_roommates))")

main() {
  for roommate in ${roommates[@]}; do
    # echo "would charge $roommate $cost_per"
    venmo charge "$roommate" "$cost_per" "$note" &
  done
}

main
